import {
	ClerkProvider,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs/app-beta';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

function SignInButton() {
	return (
		<>
			<SignedIn>
				<UserButton
					appearance={{
						elements: {
							avatarBox: 'w-10 h-10',
						},
					}}
				/>
			</SignedIn>
			<SignedOut>
				<Link
					href={'/sign-in'}
					className="rounded-lg border-2 border-white p-2"
				>
					Sign In
				</Link>
			</SignedOut>
		</>
	);
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ClerkProvider
				appearance={{
					variables: {
						colorPrimary: '#10B981',
					},
				}}
			>
				<body className={inter.className}>
					<div className="flex items-center justify-between bg-emerald-500 p-4 text-white">
						<div>
							<Link href={'/'} className="text-xl">
								Resource Packs
							</Link>
						</div>
						<div className="flex items-center gap-4">
							<Link
								href={'/packs'}
								className="rounded-lg border-2 border-white p-2"
							>
								Packs
							</Link>
							<Link
								href={'/upload'}
								className="rounded-lg border-2 border-white p-2"
							>
								Upload
							</Link>
							<SignInButton />
						</div>
					</div>
					{children}
				</body>
			</ClerkProvider>
		</html>
	);
}
