import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex items-center justify-between bg-emerald-500 p-4 text-white">
					<div>
						<Link href={'/'} className="text-xl">
							Resource Packs
						</Link>
					</div>
					<div className="flex gap-4">
						<Link
							href={'/packs'}
							className="rounded-lg border-2 border-white p-2"
						>
							Packs
						</Link>
						<Link
							href={'/upload'}
							className="rounded-lg border-2 border-white p-2"
						>
							Upload
						</Link>
						<Link href={'/'} className="rounded-lg border-2 border-white p-2">
							Sign In
						</Link>
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
